# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  openai-chat-completions-request-payload-projection.json
#   version:   0.75.0

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import ConfigDict, Field, StrictBool

from nemoguardrails.server.experimental.provider.payload import (
    GuardedContentModel,
    GuardedRequestModel,
)


class ChatCompletionsUserMessageProjection(GuardedContentModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content: Annotated[str, Field(min_length=1)]
    name: Any | None = None
    role: Literal["user"]


class ChatCompletionsGuardedRequestProjection(GuardedRequestModel):
    model_config = ConfigDict(
        extra="allow",
    )
    audio: None = None
    function_call: None = None
    functions: None = None
    messages: Annotated[list[ChatCompletionsUserMessageProjection], Field(max_length=1, min_length=1)]
    modalities: None = None
    n: Literal[1] = 1
    parallel_tool_calls: None = None
    prediction: None = None
    response_format: None = None
    stream: StrictBool = False
    tool_choice: None = None
    tools: None = None
    web_search_options: None = None
