# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  openai-chat-completions-response-payload-projection.json
#   version:   0.75.0

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import ConfigDict, Field

from nemoguardrails.server.experimental.provider.payload import (
    GuardedContentModel,
    GuardedPayloadModel,
)


class ChatCompletionsAssistantMessageProjection(GuardedContentModel):
    model_config = ConfigDict(
        extra="allow",
    )
    annotations: list[Any] | None = None
    audio: None = None
    content: Annotated[str, Field(min_length=1)]
    function_call: None = None
    reasoning_content: None = None
    refusal: None = None
    role: Literal["assistant"]
    tool_calls: None = None


class ChatCompletionsChoiceProjection(GuardedContentModel):
    model_config = ConfigDict(
        extra="allow",
    )
    finish_reason: Any | None = None
    index: Any | None = None
    logprobs: None = None
    message: ChatCompletionsAssistantMessageProjection


class ChatCompletionsGuardedResponseProjection(GuardedPayloadModel):
    model_config = ConfigDict(
        extra="allow",
    )
    choices: Annotated[list[ChatCompletionsChoiceProjection], Field(max_length=1, min_length=1)]
