# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Render and document proxy failures in the OpenAI-compatible format."""

import json

from pydantic import BaseModel

from nemoguardrails.server.experimental._buffered_kernel import (
    InspectionStage,
    OperationBlocked,
    OperationCheckFailed,
    OperationModificationUnsupported,
    OperationProjectionFailed,
)
from nemoguardrails.server.experimental._guarded_operation import (
    InvalidGuardedPayload,
    UnsupportedGuardedRepresentation,
)
from nemoguardrails.server.experimental._http_kernel import (
    BufferedHttpResponse,
    HttpFailureKind,
    HttpOperationFailed,
)
from nemoguardrails.server.experimental.provider.errors import ProviderErrorMapping, ProviderErrorResponse


class OpenAIProxyErrorDetails(BaseModel):
    """Describe OpenAI-compatible details generated by the proxy."""

    message: str
    type: str
    param: str | None
    code: str


class OpenAIProxyErrorResponse(BaseModel):
    """Describe an OpenAI-compatible proxy error response."""

    error: OpenAIProxyErrorDetails


def _error_response(
    status_code: int,
    message: str,
    error_type: str,
    code: str,
    param: str | None = None,
) -> BufferedHttpResponse:
    """Create a compact OpenAI-compatible JSON error response."""
    body = json.dumps(
        {
            "error": {
                "message": message,
                "type": error_type,
                "param": param,
                "code": code,
            }
        },
        separators=(",", ":"),
    ).encode()
    return BufferedHttpResponse(status_code, ((b"content-type", b"application/json"),), body)


def render_openai_error(
    outcome: (
        OperationBlocked
        | OperationCheckFailed
        | OperationModificationUnsupported
        | OperationProjectionFailed
        | HttpOperationFailed
    ),
) -> BufferedHttpResponse:
    """Render one typed proxy outcome with the OpenAI-compatible envelope."""

    if isinstance(outcome, OperationBlocked):
        return _error_response(
            400,
            outcome.decision.message,
            "guardrails_violation",
            "content_blocked",
            outcome.decision.rule,
        )
    if isinstance(outcome, OperationCheckFailed):
        return _error_response(
            502,
            "Guardrails content inspection failed.",
            "proxy_error",
            f"guardrails_{outcome.stage.value}_check_failed",
        )
    if isinstance(outcome, OperationModificationUnsupported):
        if outcome.stage is InspectionStage.INPUT:
            return _error_response(
                422,
                "The guarded request content cannot be replaced.",
                "unsupported_request",
                "request_content_not_replaceable",
            )
        return _error_response(
            502,
            "The guarded provider response content cannot be replaced.",
            "unsupported_response",
            "response_content_not_replaceable",
        )
    if isinstance(outcome, HttpOperationFailed):
        status_code, error_type, message = {
            HttpFailureKind.INVALID_CONTENT_LENGTH: (400, "invalid_request_error", "Invalid Content-Length."),
            HttpFailureKind.REQUEST_BODY_TOO_LARGE: (413, "request_too_large", "The request body is too large."),
            HttpFailureKind.UPSTREAM_REQUEST_FAILED: (502, "proxy_error", "The upstream request failed."),
            HttpFailureKind.RESPONSE_BODY_TOO_LARGE: (502, "proxy_error", "The upstream response is too large."),
        }[outcome.kind]
        return _error_response(status_code, message, error_type, outcome.kind.value)
    if outcome.stage is InspectionStage.INPUT:
        if isinstance(outcome.failure, InvalidGuardedPayload):
            return _error_response(400, str(outcome.failure), "invalid_request_error", "invalid_json")
        if isinstance(outcome.failure, UnsupportedGuardedRepresentation):
            return _error_response(415, str(outcome.failure), "unsupported_request", outcome.failure.code)
        return _error_response(
            422,
            "The OpenAI Chat Completions request is outside the guarded profile.",
            "unsupported_request",
            "unsupported_chat_completions_shape",
        )
    return _error_response(
        502,
        "The OpenAI Chat Completions response is outside the guarded profile.",
        "unsupported_response",
        "unsupported_chat_completions_response_shape",
    )


OPENAI_ERROR_MAPPING = ProviderErrorMapping(
    renderer=render_openai_error,
    responses=(
        ProviderErrorResponse(
            400,
            OpenAIProxyErrorResponse,
            "Invalid request framing, malformed JSON, or content rejected by Guardrails.",
        ),
        ProviderErrorResponse(
            413,
            OpenAIProxyErrorResponse,
            "Request body rejected by the proxy size limit.",
        ),
        ProviderErrorResponse(
            415,
            OpenAIProxyErrorResponse,
            "Request representation unsupported by the guarded proxy path.",
        ),
        ProviderErrorResponse(
            422,
            OpenAIProxyErrorResponse,
            "Request shape or configured Guardrails unsupported by the guarded proxy path.",
        ),
        ProviderErrorResponse(
            502,
            OpenAIProxyErrorResponse,
            "Upstream forwarding or Guardrails processing failed in the proxy.",
        ),
    ),
)
